In [1]:
import pandas as pd

In [2]:
policy_df = pd.read_csv('../data/raw/policy_data.csv')

In [35]:
policy_df

   Policy_ID  Age  Sum_Assured  Annual_Premium  Policy_Term
0       1001   35      1000000         12000.0           20
1       1002   -5      1500000         18000.0           15
2       1003   29       750000             NaN           25
3       1004   51      2000000         26000.0           10
4       1005  138      1250000         15000.0           18

In [4]:
policy_df.isnull()

   Policy_ID    Age  Sum_Assured  Annual_Premium  Policy_Term
0      False  False        False           False        False
1      False  False        False           False        False
2      False  False        False            True        False
3      False  False        False           False        False
4      False  False        False           False        False

In [5]:
policy_df.isnull().sum()

Policy_ID         0
Age               0
Sum_Assured       0
Annual_Premium    1
Policy_Term       0
dtype: int64

In [6]:
policy_df["Age"] < 0

0    False
1     True
2    False
3    False
4    False
Name: Age, dtype: bool

In [7]:
policy_df[policy_df["Age"] < 0]

   Policy_ID  Age  Sum_Assured  Annual_Premium  Policy_Term
1       1002   -5      1500000         18000.0           15

In [8]:
policy_df[policy_df["Age"] > 100]

   Policy_ID  Age  Sum_Assured  Annual_Premium  Policy_Term
4       1005  138      1250000         15000.0           18

In [9]:
policy_df[policy_df["Annual_Premium"].isnull()]

   Policy_ID  Age  Sum_Assured  Annual_Premium  Policy_Term
2       1003   29       750000             NaN           25

In [10]:
def check_negative_age(df):
    return df[df["Age"]<0]

In [11]:
check_negative_age(policy_df)

   Policy_ID  Age  Sum_Assured  Annual_Premium  Policy_Term
1       1002   -5      1500000         18000.0           15

In [12]:
def check_age_ceiling(df):
    return df[df["Age"]>100]

In [13]:
check_age_ceiling(policy_df)

   Policy_ID  Age  Sum_Assured  Annual_Premium  Policy_Term
4       1005  138      1250000         15000.0           18

In [14]:
def check_missing_premium(df):
    return df[df["Annual_Premium"].isnull()]

In [15]:
check_missing_premium(policy_df)

   Policy_ID  Age  Sum_Assured  Annual_Premium  Policy_Term
2       1003   29       750000             NaN           25

In [16]:
def check_negative_sum_assured(df):
    return df[df["Sum_Assured"]<0]

In [17]:
check_negative_sum_assured(policy_df)

Empty DataFrame
Columns: [Policy_ID, Age, Sum_Assured, Annual_Premium, Policy_Term]
Index: []

In [18]:
negative_age = check_negative_age(policy_df)
negative_age

   Policy_ID  Age  Sum_Assured  Annual_Premium  Policy_Term
1       1002   -5      1500000         18000.0           15

In [19]:
negative_age["Issue"] = "Negative Age"
negative_age

   Policy_ID  Age  Sum_Assured  Annual_Premium  Policy_Term         Issue
1       1002   -5      1500000         18000.0           15  Negative Age

In [32]:
#final validation function

def check_negative_age(df):
    failures = df[(df["Age"]<0)]

    report = pd.DataFrame({
        "Policy_ID": failures["Policy_ID"],
        "Field": "Age",
        "Value": failures["Age"],
        "Issue": "Negative Age"
    })
    return report

def check_maximum_age(df):
    failures = df[(df["Age"]>100)]

    report = pd.DataFrame({
        "Policy_ID": failures["Policy_ID"],
        "Field": "Age",
        "Value": failures["Age"],
        "Issue": "Age Above Maximum"
    })
    return report

def check_missing_age(df):
    failures = df[(df["Age"].isnull())]

    report = pd.DataFrame({
        "Policy_ID": failures["Policy_ID"],
        "Field": "Age",
        "Value": failures["Age"],
        "Issue": "Missing Age"
    })
    return report

def check_negative_premium(df):
    failures = df[(df["Annual_Premium"]<0)]

    report = pd.DataFrame({
        "Policy_ID": failures["Policy_ID"],
        "Field": "Annual_Premium",
        "Value": failures["Annual_Premium"],
        "Issue": "Negative Premium"
    })
    return report

def check_missing_premium(df):
    failures = df[(df["Annual_Premium"].isnull())]

    report = pd.DataFrame({
        "Policy_ID": failures["Policy_ID"],
        "Field": "Annual_Premium",
        "Value": failures["Annual_Premium"],
        "Issue": "Missing Premium"
    })
    return report

def check_negative_sum_assured(df):
    failures = df[df["Sum_Assured"]<0]

    report = pd.DataFrame({
        "Policy_ID": failures["Policy_ID"],
        "Field": "Sum_Assured",
        "Value": failures["Sum_Assured"],
        "Issue": "Negative Sum Assured"
    })
    return report

def check_missing_sum_assured(df):
    failures = df[df["Sum_Assured"].isnull()]

    report = pd.DataFrame({
        "Policy_ID": failures["Policy_ID"],
        "Field": "Sum_Assured",
        "Value": failures["Sum_Assured"],
        "Issue": "Invalid Sum Assured"
    })
    return report

def check_negative_policy_term(df):
    failures = df[df["Policy_Term"]<0]

    report = pd.DataFrame({
        "Policy_ID": failures["Policy_ID"],
        "Field": "Policy_Term",
        "Value": failures["Policy_Term"],
        "Issue": "Negative Policy Term"
        })
    return report

def check_missing_policy_term(df):
    failures = df[df["Policy_Term"].isnull()]

    report = pd.DataFrame({
        "Policy_ID": failures["Policy_ID"],
        "Field": "Policy_Term",
        "Value": failures["Policy_Term"],
        "Issue": "Missing Policy Term"
        })
    return report

In [33]:
def validate_policy_data(df):
    report = pd.concat([
            check_negative_age(df),
            check_maximum_age(df),
            check_missing_age(df),
            check_negative_premium(df),
            check_missing_premium(df),
            check_negative_sum_assured(df),
            check_missing_sum_assured(df),
            check_negative_policy_term(df),
            check_missing_policy_term(df)
            ], ignore_index=True)
    return report

In [34]:
validate_policy_data(policy_df)

   Policy_ID           Field  Value              Issue
0       1002             Age   -5.0       Negative Age
1       1005             Age  138.0  Age Above Maximum
2       1003  Annual_Premium    NaN    Missing Premium